dist:     focal
sudo:     required  # используем Virtual Machine (а не Docker container)

language: c

os:
    - linux

branches:
  only:
    - other

compiler:
  - gcc

install:
  - sudo apt-get install valgrind
  - sudo pip3 install cpplint
  - sudo apt install cppcheck

script:
- mkdir build
- cd build
- cmake ..
- cmake —build .
- ctest —output-on-failure