dist:     focal
sudo:     required  # используем Virtual Machine (а не Docker container)

language: c

branches:
  only:
    - other

compiler:
  - gcc

install:
  - sudo apt-get install valgrind
  - sudo pip3 install cpplint
  - sudo apt install cppcheck

script:
- mkdir IT1/cmake-build-debug && cd IT1/cmake-build-debug/
- cmake ..
- make clean && make